<?php
$arrEnginges = array();

// 2020-12-11/fh: 'urlReal' introduced in context with intercepting 'sorry.php' page.
// 2021-03-30/fh: 'noFrameBrowserIntranet' and 'noFrameBrowserExternal' to hold a comma-separated list of browsers
//                 that cannot show the target page inside a HTML frame. Empty for none, '*' for all browsers.
// 2022-04-19/fh: Origial web-API url added in key 'urlOrig', this is not used on OLD lib4ri.ch but will be used on the new site!

$arrEnginges['articles']['back']      = '/resources/databases/databases.html';
$arrEnginges['articles']['backimage'] = '/site/images/pfeil_databases.png';
$arrEnginges['articles']['main'] = array(
    'Web of Science Core Collection' => array(
      'noFrameBrowserIntranet' => 'Chrome,Edge,Safari',
      'noFrameBrowserExternal' => 'Firefox,Chrome,Edge,Safari',		/* because there is no network-external access at all */
//    'url'                   => 'https://gateway.webofknowledge.com/gateway/Gateway.cgi?GWVersion=2&SrcApp=LIB4RI_WEB&SrcAuth=LIB4RI&DestApp=UA&ServiceName=TransferToWoS&DestLinkType=GeneralSearchSummary&Func=Links&topic=###',
//    'url'                   => 'https://www.webofscience.com/wos/woscc/general-summary?query=TI%3d%28###%29%20OR%20AU%3d%28###%29',
      'url'                   => 'https://www.webofscience.com/wos/woscc/general-summary?query=ALL%3d%28###%29',
      'info'           	      => '/resources/databases/databases.html#/?slide=Web-of-Science',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'Scopus'        	      => array(
      'url'                   => '/site/search/sorry.php?type=articles&site=Scopus&q=###',
      'urlReal'               => 'https://www.scopus.com/results/results.uri?src=s&searchterm1=###&sot=b&s=TITLE-ABS-KEY-AUTH(###)&sid=new',
      'info'           	      => '/resources/databases/databases.html#/?slide=Scopus',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),    
      'Central Discovery Index'   => array(
      'noFrameBrowserIntranet' => 'Chrome,Edge,Safari',
      'noFrameBrowserExternal' => 'Chrome,Edge,Safari',
      'url'                   => 'https://lib4ri.swisscovery.slsp.ch/discovery/search?query=any,contains,###&tab=CDI&search_scope=CentralIndex&vid=41SLSP_LIB:GO&lang=en&offset=0',
      'info'           	      => '/resources/databases/databases.html++/category/36/#/?slide=Central-Discovery-Index-CDI',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'CORE'                 => array(
      'noFrameBrowserIntranet' => 'Chrome,Edge,Safari',
      'noFrameBrowserExternal' => 'Chrome,Edge,Safari',
      'url'                   => 'https://core.ac.uk/search?q=###',
      'info'           	      => '/resources/databases/databases.html#/?slide=CORE',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '%20AND%20',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'OAIster'                 => array(
      'url'                   => 'https://oaister.worldcat.org/search?qt=wc_org_oaister&q=###&scope=0&oldscope=&wcsbtn2w=Suche%28n%29&dblist=239',
      'info'           	      => '/resources/databases/databases.html#/?slide=OAister',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'BASE'                    => array(
      'url'                   => 'https://www.base-search.net/Search/Results?lookfor=###&type=all&lem=0&lem=1&refid=dcbasde',
      'info'           	      => '/resources/databases/databases.html#/?slide=BASE-Bielefeld-Academic-Search-Engine',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'Mendeley'        	      => array(
 //   'url'                   => 'https://www.mendeley.com/research-papers/search/?query=###',
      'url'                   => 'https://www.mendeley.com/search/?query=###',
      'info'           	      => '/resources/databases/databases.html#/?slide=Mendeley',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'Google Scholar'          => array(
      'urlOrig'               => 'http://scholar.google.com/scholar?hl=en&q=###',
      'url'                   => '/site/search/find/scholar.php?hl=en&q=###',
      'info'                  => '/resources/databases/databases.html#/?slide=Google-Scholar',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'DOAJ - Articles'         => array(
      'url'                   => 'https://www.doaj.org/search/articles?ref=homepage-box&source=%7B%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%22###%22%2C%22default_operator%22%3A%22AND%22%7D%7D%7D',
//    'url'                   => 'https://www.doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%22###%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22_type%22:%22article%22}}]}}}}}',
      'info'           	      => '/resources/databases/databases.html#/?slide=DOAJ-Directory-of-Open-Access-Journals',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'Dimensions'         => array(
      'url'                   => 'https://app.dimensions.ai/discover/publication?search_mode=content&search_text=###&search_type=kws&search_field=full_search',
      'info'           	      => '/resources/databases/databases.html#/?slide=Dimensions',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'swisscovery articles'         => array(
//    'url'                   => 'https://swisscovery.slsp.ch/discovery/search?tab=41SLSP_NETWORK&vid=41SLSP_NETWORK:VU1_UNION&search_scope:DN_and_CI&query=any,contains,###',
      'url'                   => 'https://lib4ri.swisscovery.slsp.ch/discovery/search?tab=CDI&search_scope=CentralIndex&vid=41SLSP_LIB:GO&lang=en&offset=0&query=any,contains,###',
      'info'           	      => '/resources/databases/databases.html#/?slide=swisscovery',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
	
  );

$arrEnginges['articles']['Technology'] = array(
    'Inspec'                  => array(
      'noFrameBrowserIntranet' => 'Chrome,Edge,Safari',
      'noFrameBrowserExternal' => '*', /* 'Firefox,Chrome,Edge,Safari',	 */	/* because there is no network-external access at all */
//    'url'                   => 'https://gateway.isiknowledge.com/gateway/Gateway.cgi?GWVersion=2&SrcApp=LIB4RI_WEB&SrcAuth=LIB4RI&DestApp=INSPEC&ServiceName=TransferToWoS&DestLinkType=GeneralSearchSummary&Func=Links&topic=###',
//    'url'                   => 'https://gateway.webofknowledge.com/gateway/Gateway.cgi?GWVersion=2&SrcApp=LIB4RI_WEB&SrcAuth=LIB4RI&DestApp=INSPEC&ServiceName=TransferToWoS&DestLinkType=GeneralSearchSummary&Func=Links&topic=###&action=search',
      'url'                   => 'https://www.webofscience.com/wos/inspec/general-summary?TS=###',
      'info'     	      => '/resources/databases/databases.html#/?slide=Inspec',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
/**** Removed link 16-Jan-2014 ****
'Technology Research Database'    => array(
      'url'                   => 'http://search.proquest.com/technology/results/13E5FE5D76E8E6B103/1/$5bqueryType$3dbasic:technology$3b+sortType$3drelevance$3b+searchTerms$3d$5b$3cAND$7ccitationBodyTags:###$3e$5d$3b+searchParameters$3d$7bNAVIGATORS$3dsourcetypenav,pubtitlenav,objecttypenav,languagenav$28filter$3d200$2f0$2f*$29,decadenav$28filter$3d110$2f0$2f*,sort$3dname$2fascending$29,yearnav$28filter$3d1100$2f0$2f*,sort$3dname$2fascending$29,yearmonthnav$28filter$3d120$2f0$2f*,sort$3dname$2fascending$29,monthnav$28sort$3dname$2fascending$29,daynav$28sort$3dname$2fascending$29,+RS$3dOP,+chunkSize$3d20,+instance$3dprod.academic,+ftblock$3d670835+670832+8+163000+163209+163008+660833+740834+740833+660845+670826+209+660843,+removeDuplicates$3dtrue$7d$3b+metaData$3d$7bUsageSearchMode$3dQuickSearch,+dbselections$3d10000015,+fdbok$3dN$7d$5d?accountid=28439',
      'info'           	      => '/resources/databases/databases.html#/?slide=CSA-Technology-Research-Database',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
*/
  );
$arrEnginges['articles']['Science'] = array(
    'arXiv.org'               => array(
      'url'                   => 'https://arxiv.org/find/all/1/all:###/0/1/0/all/0/1',
      'info'           	      => '/resources/databases/databases.html#/?slide=arXiv-org',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => true,
      'keywordSeparator'      => '+',
      'addBefore'             => '+AND+',
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'CAB Abstracts'           => array(
      'noFrameBrowserIntranet' => 'Chrome,Edge,Safari',
      'noFrameBrowserExternal' => '*', /* 'Firefox,Chrome,Edge,Safari',	 */	/* because there is no network-external access at all */
//    'url'                   => 'https://gateway.webofknowledge.com/gateway/Gateway.cgi?GWVersion=2&SrcApp=LIB4RI_WEB&SrcAuth=LIB4RI&DestApp=CABI&ServiceName=TransferToWoS&DestLinkType=GeneralSearchSummary&Func=Links&topic=###',
      'url'                   => 'https://www.webofscience.com/wos/cabi/general-summary?TS=###',
      'info'           	      => '/resources/databases/databases.html#/?slide=Web-of-Science',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'JACoW' 		      => array(
      'url'                   => 'https://search.cern.ch/Pages/results.aspx?k=+domain%3Daccelconf%2Eweb%2Ecern%2Ech+###%20%20FileExtension%3Dpdf%20-url%3Aabstract%20-url%3Aaccelconf/jacow#Default=%7B%22k%22%3A%22###%22%2C%22r%22%3A%5B%7B%22n%22%3A%22FileType%22%2C%22t%22%3A%5B%22equals(%5C%22pdf%5C%22)%22%5D%2C%22o%22%3A%22or%22%2C%22k%22%3Afalse%2C%22m%22%3Anull%7D%2C%7B%22n%22%3A%22domain%22%2C%22t%22%3A%5B%22%5C%22%C7%82%C7%82616363656c636f6e662e7765622e6365726e2e6368%5C%22%22%5D%2C%22o%22%3A%22and%22%2C%22k%22%3Afalse%2C%22m%22%3Anull%7D%5D%7D',
      'info'           	      => '/resources/databases/databases.html#/?slide=Joint-Accelerator-Conferences-Website',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
/**** Removed link 11-Jan-2019 ****
    'MathSciNet'              => array(
      'url'                   => 'https://mathscinet.ams.org/mathscinet/search/publications.html?pg4=AUCN&s4=&co4=AND&pg5=TI&s5=&co5=AND&pg6=PC&s6=&co6=AND&pg7=ALLF&s7=###&co7=AND&Submit=Suche&dr=all&yrop=eq&arg3=&yearRangeFirst=&yearRangeSecond=&pg8=ET&s8=All&review_format=html',
      'info'           	      => '/resources/databases/databases.html#/?slide=MathSciNet',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
*/
    'PubMed'      	      => array(
//    'url'                   => 'https://www.ncbi.nlm.nih.gov/pubmed/?otool=ichlrielib&term=###',
      'urlOrig'               => 'https://pubmed.ncbi.nlm.nih.gov/?otool=ichlrielib&term=###',
      'url'                   => '/site/search/find/pubmed.php?q=###',
      'info'           	      => '/resources/databases/databases.html#/?slide=PubMed',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
  );

$arrEnginges['journals']['back']			= '/resources/journals.html';
$arrEnginges['journals']['backimage']	= '/site/images/pfeil_journals.png';
$arrEnginges['journals']['main'] = array(
    'Journals at Lib4RI' => array(
      'noFrameBrowserIntranet' => 'Chrome,Edge,Safari',
      'noFrameBrowserExternal' => 'Chrome,Edge,Safari',
//    'url'                   => 'https://sfx.ethz.ch/sfx_lib4ri/az/?param_lang_save=eng&param_letter_group_save=&param_perform_save=searchTitle&param_letter_group_script_save=&param_chinese_checkbox_save=0&param_services2filter_save=getFullTxt&param_current_view_save=table&param_jumpToPage_save=1&param_type_save=textSearch&param_textSearchType_save=contains&param_type_value=textSearch&param_jumpToPage_value=&param_pattern_value=###&param_textSearchType_value=contains&param_chinese_checkbox_value=0',
      'url'                   => 'https://lib4ri.swisscovery.slsp.ch/discovery/jsearch?query=any,contains,###&tab=jsearch_slot&vid=41SLSP_LIB:GO&offset=0&journals=any,###',
      'info'           	      => '/resources/journals.html',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'Journals in swisscovery' => array(
      'noFrameBrowserIntranet' => 'Chrome,Edge,Safari',
      'noFrameBrowserExternal' => 'Chrome,Edge,Safari',
//    'url'                    => 'https://lib4ri.swisscovery.slsp.ch/discovery/search?query=title,contains,###&tab=41SLSP_LIB_DN_CI&search_scope=DN_and_CI&vid=41SLSP_LIB:GO&mfacet=rtype,include,journals,1&mfacet=rtype,include,newspapers,1&mfacet=tlevel,include,online_resources,2&lang=en&offset=0',
      'url'                    => 'https://lib4ri.swisscovery.slsp.ch/discovery/search?query=title,contains,###&tab=41SLSP_LIB_DN_CI&search_scope=DN_and_CI&vid=41SLSP_LIB:GO&mfacet=rtype,include,journals,1&mfacet=rtype,include,newspapers,1&lang=en&offset=0',
      'info'    	      => '/resources/journals.html',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => true,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ), 
    'Journal Citation Reports'=> array(
      'noFrameBrowserIntranet' => 'Chrome,Edge',
      'noFrameBrowserExternal' => '',
//    'url'                   => 'https://jcr.incites.thomsonreuters.com/JCRMasterSearchAction.action?pg=SEARCH&searchString=###',
//    'url'                   => 'https://jcr.clarivate.com',
      'url'                   => 'https://jcr.clarivate.com/JCRMasterSearchAction.action?pg=SEARCH&searchString=###',	/* checked+OK, but wants Cookies keys */
//    'url'                   => '/site/search/find/incites.php?q=###', /* would work in FireFox, but not in Chrome */
      'info'           	      => '/resources/journals.html#master',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '%20',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'DOAJ - Journals' => array(
      'url'                   => 'https://www.doaj.org/search/journals?ref=homepage-box&source=%7B%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%22###%22%2C%22default_operator%22%3A%22AND%22%7D%7D%7D',
//    'url'                   => 'https://www.doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%22###%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22_type%22:%22journal%22}}]}}}}}',
      'info'           	      => '/resources/databases/databases.html#/?slide=DOAJ-Directory-of-Open-Access-Journals',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'Master Journal List' => array(
//    'url'                 => 'http://science.thomsonreuters.com/cgi-bin/jrnlst/jlresults.cgi?PC=MASTER&Word=###',
      'url'                   => 'https://mjl.clarivate.com/cgi-bin/jrnlst/jlresults.cgi?PC=MASTER&Word=###',
//    'url'                   => '/site/search/master_list.php?q=###',
      'info'           	      => '/resources/journals.html#master',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'SHERPA/RoMEO' => array(
//    'url'                   => 'https://www.sherpa.ac.uk/romeo/search.php?la=en&jtitle=###&jrule=contains',
// 2020-06-17/fh:
      'urlOrig'               => 'https://v2.sherpa.ac.uk/cgi/search/publication/basic?screen=Search&publication_title-auto=###',
      'url'                   => '/site/search/find/sherpa.php?q=###',
      'info'           	      => '/resources/journals.html#sherpa',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => true,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'EZB' => array(
      'url'                   => 'https://rzblx1.uni-regensburg.de/ezeit/searchres.phtml?bibid=AAAAA&colors=7&lang=en&jq_type1=KT&jq_term1=###',
      'info'           	      => '/resources/journals.html#ezb',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => true,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'ZDB' => array(
      'url'                   => 'https://zdb-katalog.de/list.xhtml?t=###&key=tit',
      'info'           	      => '/resources/journals.html#zdb',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => true,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    )        
  );

$arrEnginges['books']['back']		= '/resources/books.html';
$arrEnginges['books']['backimage']	= '/site/images/pfeil_books.png';
$arrEnginges['books']['main'] = array(
//    'Lib4RI E-Book Catalogue' => array(
//    'url'                   => 'https://search.ebscohost.com/login.aspx?direct=true&bquery=###+AND+(PT+ebook+OR+PT+book)&ssl=Y&type=0&site=eds-live&custid=ns226431&groupid=main&profile=eds&authtype=ip,guest',
//      'info'           	      => '/news.html++/year/2016/item/145/',
//      'replaceTag'            => '###',
//      'replaceGermanVowel'    => false,
//      'keywordSeparator'      => '+',
//      'addBefore'             => false,
//      'enabled'               => true,
//      'prio'                  => 1,
//    ),
    'Lib4RI'     => array(
      'noFrameBrowserIntranet' => 'Chrome,Edge,Safari',
      'noFrameBrowserExternal' => 'Chrome,Edge,Safari',
      'url'                   => 'https://lib4ri.swisscovery.slsp.ch/discovery/search?query=any,contains,###&tab=LibraryCatalog&search_scope=MyInstitution&vid=41SLSP_LIB:GO&lang=en&offset=0',
      'info'           	      => '/resources/books.html',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),

    'swisscovery'     => array(
      'noFrameBrowserIntranet' => 'Chrome,Edge,Safari',
      'noFrameBrowserExternal' => 'Chrome,Edge,Safari',
      'url'                   => 'https://lib4ri.swisscovery.slsp.ch/discovery/search?query=any,contains,###&tab=41SLSP_LIB_DN_CI&search_scope=DN_and_CI&vid=41SLSP_LIB:GO&facet=rtype,exclude,articles&facet=rtype,exclude,newspaper_articles&lang=en&offset=0',
//    'url'                   => 'https://lib4ri.swisscovery.slsp.ch/discovery/search?query=any,contains,###&tab=41SLSP_LIB_DN_CI&search_scope=DN_and_CI&vid=41SLSP_LIB:GO&lang=en&offset=0',
      'info'           	      => '/resources/books.html',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
//    'swissbib'                => array(
//      'url'                   => 'https://www.swissbib.ch/Search/Results?lookfor=###',
//      'info'                  => '/resources/books.html#swissbib',
//      'replaceTag'            => '###',
//      'replaceGermanVowel'    => false,
//      'keywordSeparator'      => '+',
//      'addBefore'             => false,
//      'enabled'               => true,
 //     'prio'                  => 1,
//    ),
    'WorldCat' => array(
      'url'                   => 'https://www.worldcat.org/search?qt=worldcat_org_all&q=###',
      'info'           	      => '/resources/books.html#worldcat',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ), 
    'KVK' 		      => array(
      'url'                   => 'https://kvk.bibliothek.kit.edu/hylib-bin/kvk/nph-kvk2.cgi?maske=kvk-redesign&lang=de&title=KIT-Bibliothek%3A+Karlsruher+Virtueller+Katalog+KVK+%3A+Ergebnisanzeige&head=%2F%2Fkvk.bibliothek.kit.edu%2Fasset%2Fhtml%2Fhead.html&header=%2F%2Fkvk.bibliothek.kit.edu%2Fasset%2Fhtml%2Fheader.html&spacer=%2F%2Fkvk.bibliothek.kit.edu%2Fasset%2Fhtml%2Fspacer.html&footer=%2F%2Fkvk.bibliothek.kit.edu%2Fasset%2Fhtml%2Ffooter.html&css=none&input-charset=utf-8&ALL=###&TI=&AU=&CI=&ST=&PY=&SB=&SS=&PU=&VERBUENDE=&kataloge=SWB&kataloge=BVB&kataloge=NRW&kataloge=HEBIS&kataloge=HEBIS_RETRO&kataloge=KOBV_SOLR&kataloge=GBV&kataloge=DDB&kataloge=STABI_BERLIN&OESTERREICH=&kataloge=BIBOPAC&kataloge=LBOE&kataloge=OENB&SCHWEIZ=&kataloge=SWISSBIB&kataloge=HELVETICAT&kataloge=BASEL&kataloge=ETH&kataloge=VKCH_RERO&ref=direct&client-js=yes',
      'info'           	      => '/resources/books.html#kvk',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'Book Trade' 	      => array(
      'url'                   => 'https://kvk.bibliothek.kit.edu/hylib-bin/kvk/nph-kvk2.cgi?maske=kvk-last&title=KIT+Library%3A+Karlsruhe+Virtual+Catalog+KVK+%3A+Search+results&head=http%3A%2F%2Fwww.ubka.uni-karlsruhe.de%2Fkvk%2Fkvk%2Fkvk-kit-head-en-2010-11-08.html&header=http%3A%2F%2Fwww.ubka.uni-karlsruhe.de%2Fkvk%2Fkvk%2Fkvk-kit-header-en-2010-11-08.html&spacer=http%3A%2F%2Fwww.ubka.uni-karlsruhe.de%2Fkvk%2Fkvk%2Fkvk-kit-spacer-en-2010-11-08.html&footer=http%3A%2F%2Fwww.ubka.uni-karlsruhe.de%2Fkvk%2Fkvk%2Fkvk-kit-footer-en-2010-11-08.html&css=none&lang=en&input-charset=utf-8&kvk-session=2FHU9A7Y&ALL=###&target=_blank&Timeout=120&TI=&PY=&AU=&SB=&CI=&SS=&ST=&PU=&kataloge=AMAZON_DE&kataloge=AMAZON_US&kataloge=KNO&kataloge=ZVAB',
      'info'           	      => '/resources/books.html#kvk',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'Google Books'            => array(
      'urlOrig'               => 'https://www.google.com/search?hl=en&tbo=p&tbm=bks&q=###',	
      'url'                   => '/site/search/find/gbooks.php?q=###',
      'info'                  => '/resources/books.html#google_books',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'Open Library'            => array(
      'url'                   => 'https://openlibrary.org/search?q=###&has_fulltext=true',
      'info'           	      => '/resources/books.html#open_library',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'DOAB'          	      => array(
//    'url'                   => 'https://www.doabooks.org/doab?func=search&template=&query=###&x=0&y=0',
      'url'                   => 'https://directory.doabooks.org/discover?submit=&query=###',
      'info'           	      => '/resources/books.html#doab',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    )
  );

$arrEnginges['references']['back']	= '/resources/reference.html';
$arrEnginges['references']['backimage']	= '/site/images/pfeil_reference.png';
$arrEnginges['references']['main'] = array(
    'Wikipedia – EN' 	      => array(
      'url'                   => 'https://www.wikipedia.org/search-redirect.php?search=###&language=en&go=++%E2%86%92++&go=Go',
      'info'           	      => '/resources/reference.html#general',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'Wikipedia – DE' 	      => array(
      'url'                   => 'https://www.wikipedia.org/search-redirect.php?search=###&language=de&go=++%E2%86%92++&go=Go',
      'info'           	      => '/resources/reference.html#general',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'Wikipedia – FR' 	      => array(
      'url'                   => 'https://www.wikipedia.org/search-redirect.php?search=###&language=fr&go=++%E2%86%92++&go=Go',
      'info'           	      => '/resources/reference.html#general',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'Wikipedia – IT' 	      => array(
      'url'                   => 'https://www.wikipedia.org/search-redirect.php?search=###&language=it&go=++%E2%86%92++&go=Go',
      'info'           	      => '/resources/reference.html#general',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
/*
    'Wikipedia – RR' 	      => array(
      'url'                   => 'https://www.wikipedia.org/search-redirect.php?search=###&language=rm&go=++%E2%86%92++&go=Go',
      'info'           	      => '/resources/reference.html#general',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
*/
    'Wolfram | Alpha'         => array(
//    'url'                   => '/site/search/wolframalpha.php?q=###',
      'url'                   => 'https://www.wolframalpha.com/input/?i=###',
      'info'           	      => '/resources/more/search-the-web.html#wolfram',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),

    'Britannica' 	      => array(
      'url'                   => 'https://www.britannica.com/search?query=###',
      'info'           	      => '/resources/reference.html#general',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => 'utf8_encode',
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
//    'Oxford Reference' 	      => array(
//    'url'                   => 'http://www.oxfordreference.com/views/SEARCH_RESULTS.html?q=###&x=0&y=0',
//    'info'           	      => '/resources/reference.html#general',
//    'replaceTag'            => '###',
//    'replaceGermanVowel'    => false,
//    'keywordSeparator'      => '+',
//    'addBefore'             => false,
//    'enabled'               => true,
//    'prio'                  => 1,
//   ),
// Disabled by Bobby's request from 18-Mov-2020
    'LEO E <> D' 	      => array(
      'url'                   => 'https://dict.leo.org/ende?lp=ende&lang=de&searchLoc=0&cmpType=relaxed&sectHdr=on&spellToler=&search=###',
      'info'           	      => '/resources/reference/dictionaries-.html#bi',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'LEO F <> D' 	      => array(
      'url'                   => 'https://dict.leo.org/frde?lp=frde&lang=de&searchLoc=0&cmpType=relaxed&sectHdr=on&spellToler=&search=###',
      'info'           	      => '/resources/reference/dictionaries-.html#bi',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    )
);

$arrEnginges['references']['Science & Technology'] = array(
    'ChemSpider'      	      => array(
      'url'                   => 'https://www.chemspider.com/Search.aspx?q=###',
      'info'           	      => '/resources/reference/physical-und-chemical-properties.html#chemspider',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'Elsevier Reference'      => array(
      'url'                   => 'https://www.sciencedirect.com/search/advanced?qs=###&articleTypes=EN',
      'info'           	      => '/resources/reference.html#elsevier',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
//    'Knovel'           	      => array(
//    'url'                   => 'https://app.knovel.com/web/search.v?q=###',  
//      'info'           	      => '/resources/reference.html#knovel',
//      'replaceTag'            => '###',
//      'replaceGermanVowel'    => true,
//      'keywordSeparator'      => '+',
//      'addBefore'             => false,
//      'enabled'               => true,
//      'prio'                  => 1,
//    ),
    'Springer Materials'      => array(
      'url'                   => 'https://materials.springer.com/search?searchTerm=###&propertyFacet=',
      'info'                  => '/resources/reference/physical-und-chemical-properties.html#springermat',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'Springer Reference'      => array(
      'url'                   => 'https://link.springer.com/search?query=###&showAll=false&facet-content-type=%22ReferenceWorkEntry%22',
      'info'           	      => '/resources/reference.html#springer',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'Wiley Reference'         => array(
      'url'                   => 'https://onlinelibrary.wiley.com/action/doSearch?text1=###&PubType=refWork',
      'info'           	      => '/resources/reference.html#wiley',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    )
);

$arrEnginges['institutes']['back']	= '/institutional-bibliography/eawag.html';
$arrEnginges['institutes']['backimage']	= '/site/images/pfeil_institutes.png';
$arrEnginges['institutes']['Eawag'] = array(
    'People'     	      => array(
      'url'                   => 'https://www.eawag.ch/de/suche/?q=###&tx_solr%5Bfilter%5D%5B0%5D=filtertype%253A3',
      'info'                  => '/resources/more/search-the-web.html#people_eawag',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => true,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'Publications (DORA)'     => array(
//    'url'                   => '/site/search/dora_eawag.php?q=###',
      'url'                   => 'https://www.dora.lib4ri.ch/eawag/islandora/search/###?type=dismax',
      'info'           	      => '/institutional-bibliography/eawag.html',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => true,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'Fulltext'     	      => array(
      'url'                   => 'https://www.eawag.ch/de/suche/?q=###&%5Bsubmit%5D=Suchen',
      'info'           	      => '/resources/more/search-the-web.html#full_eawag',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    )
);

$arrEnginges['institutes']['Empa'] = array(
    'People'     	      => array(
      'urlOrig'           => 'https://www.empa.ch/web/empa/home?_3_formDate=' . time() . '&p_p_id=3&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_3_struts_action=%2Fsearch%2Fsearch&_3_cur=1&_3_format=&_3_sortParam=&_3_modified=&_3_entryClassName=com.liferay.portal.model.User&_3_keywords=###',
//    'url'                   => '/site/search/empa_search_pers.php?hl=en&q=###',
      'url'                   => '/site/search/find/empa_pers.php?q=###',
      'info'           	      => '/resources/more/search-the-web.html#people_empa',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => true,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'Publications (DORA)'     => array(
//    'url'                   => '/site/search/dora_empa.php?q=###',
      'url'                   => 'https://www.dora.lib4ri.ch/empa/islandora/search/###?type=dismax',
      'info'           	      => '/institutional-bibliography/empa.html',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => true,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'Fulltext'                => array(
      'urlOrig'               => 'https://www.empa.ch/web/empa?p_p_id=3&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_3_struts_action=%2Fsearch%2Fsearch&_3_groupId=0&_3_keywords=###',
//    'url'                   => '/site/search/empa_search.php?hl=en&q=###',
      'url'                   => '/site/search/find/empa_text.php?q=###',
      'info'           	      => '/resources/more/search-the-web.html#full_empa',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    )
);

$arrEnginges['institutes']['PSI'] = array(
    'People'     	      => array(
//    'url'                   => 'https://www.psi.ch/phonebook-and-e-mail-directory?q=###&sa.x=0&sa.y=0&sa=Suche',
      'urlOrig'               => 'https://www.psi.ch/en/search/phonebook-and-e-mail-directory?keywords=###',
//    'url'                   => '/site/search/tel_psi.php?q=###',
      'url'                   => '/site/search/find/psi_pers.php?q=###',
      'info'           	      => '/resources/more/search-the-web.html#people_psi',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => true,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'Publications (DORA)'     => array(
//    'url'                 => 'https://www.psi.ch/science/scientific-highlights',
//    'url'                   => '/site/search/dora_psi.php?q=###',
      'url'                   => 'https://www.dora.lib4ri.ch/psi/islandora/search/###?type=dismax',
      'info'           	      => '/institutional-bibliography/psi.html',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'Fulltext'     	      => array(
//    'url' 		          => 'https://www.psi.ch/search/search?searchaction=%2Fsearch%2Fsearch&q=###&searchtext=Search&sprachvar=EN&cx=006264299542828176624%3Aez8g0dw8zyg&cof=FORID%3A10&ie=UTF-8#gsc.tab=0&gsc.q=###&gsc.page=1',
      'urlOrig'               => 'https://www.psi.ch/en/search?keywords=###',
//    'url'                   => '/site/search/search_psi.php?q=###',
      'url'                   => '/site/search/find/psi_text.php?q=###',
      'info'           	      => '/resources/more/search-the-web.html#full_psi',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    )
);

$arrEnginges['institutes']['WSL'] = array(
      'People'     	      => array(     
//    'url'                   => 'https://www.wsl.ch/en/about-wsl/staff.html?q=###',
//    'url'                   => 'https://www.wsl.ch/en/about-wsl/staff.html?tx_wslfilter_filter%5Bkeyword%5D=###',
      'url'                   => 'https://www.wsl.ch/en/about-wsl/organisation/staff.html?tx_wslfilter_filter%5Bkeyword%5D=###',
      'info'           	      => '/resources/more/search-the-web.html#people_wsl',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'Publications (DORA)'     => array(
//    'url'                   => '/site/search/dora_wsl.php?q=###',
      'url'                   => 'https://www.dora.lib4ri.ch/wsl/islandora/search/###?type=dismax',
      'info'                  => '/institutional-bibliography/wsl.html',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'Fulltext'    	      => array(
      'url'                  => 'https://www.wsl.ch/en/search.html?q=###',
      'info'           	      => '/resources/more/search-the-web.html#full_wsl',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    )
);

$arrEnginges['institutes']['Lib4RI'] = array(
    'Search Lib4RI website with Google'    	      => array(
      'url'                  => 'https://www.google.com/search?hl=en&num=30&q=site%3Awww.lib4ri.ch%20###',
      'info'           	      => '/resources/more/search-the-web.html#full_lib4ri',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '%20',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'Search Lib4RI website with Google (PDF only)'    	      => array(
      'url'                  => 'https://www.google.com/search?hl=en&num=30&q=site%3Awww.lib4ri.ch%20###%20filetype%3aPDF',
      'info'           	      => '/resources/more/search-the-web.html#full_lib4ri',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '%20',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'Search Lib4RI website with Google (no PDF)'    	      => array(
      'url'                  => 'https://www.google.com/search?hl=en&num=30&q=site%3Awww.lib4ri.ch%20###%20-filetype%3aPDF',
      'info'           	      => '/resources/more/search-the-web.html#full_lib4ri',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '%20',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
);

$arrEnginges['more']['back']		= '/resources/more/climate-data.html';
$arrEnginges['more']['backimage']	= '/site/images/pfeil_more.png';
$arrEnginges['more']['main'] = array(
    'Lib4RI Standards Portal' => array(
      'url'                   => 'https://lib4ri.eresearchcenter.eu/searchxml?SERVICE=ercDistributedQuerySimpleService&FUNCTION=search&ID=eresearchCenterAdvanced&Perinorm=true&queryField_identifierDI=###',
      'info'                  => '/resources/standards.html#portal',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '%20',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    )
);

$arrEnginges['more']['Dissertations'] = array(
//    'swissbib (theses)'       => array(
//      'url'                   => 'https://www.swissbib.ch/Search/Results?join=AND&bool0[]=AND&lookfor0[]=###&type0[]=AllFields&page=0&filter[]=format_str_mv%3A%22BK020300%22',
//      'info'           	      => '/resources/more/dissertations.html#/?slide=swissbib-Swiss-theses',
//      'replaceTag'            => '###',
//      'replaceGermanVowel'    => false,
//      'keywordSeparator'      => '+',
//      'addBefore'             => false,
//      'enabled'               => true,
//      'prio'                  => 1,
//    ),
    'swisscovery (theses)'       => array(
      'noFrameBrowserIntranet' => 'Chrome,Edge,Safari',
      'noFrameBrowserExternal' => 'Chrome,Edge,Safari',
      'url'                   => 'https://lib4ri.swisscovery.slsp.ch/discovery/search?query=any,contains,###&tab=41SLSP_LIB_DN_CI&search_scope=DN_and_CI&mfacet=rtype,include,dissertations,1&vid=41SLSP_LIB:GO&lang=en&offset=0',
      'info'           	      => '/resources/more/dissertations.html#/?slide=swisscovery-Swiss-theses',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'WorldCat (theses)'       => array(
      'url'                   => 'https://www.worldcat.org/search?q=####%2528x0%253Abook%2Bx4%253Athsis%2529format',
      'info'                  => '/resources/more/dissertations.html#/?slide=NDLTD-worldwide',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'NDLTD Global ETD Search' => array(
      'url'                   => 'http://search.ndltd.org/search.php?q=###',
      'info'           	      => '/resources/more/dissertations.html#/?slide=NDLTD-worldwide',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'DART Europe'     	      => array(
      'urlOrig'               => 'https://www.dart-europe.org/basic-results.php?f=n&kw%5b%5d=###',
//    'url'                   => '/site/search/dart.php?q=###',
      'url'                   => '/site/search/find/dart-eu.php?q=###',
      'info'           	      => '/resources/more/dissertations.html#/?slide=DART-Europe',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'OATD'     		      => array(
      'url'                   => 'https://oatd.org/oatd/search?q=###&form=basic',
      'info'           	      => '/resources/more/dissertations.html#/?slide=OATD-worldwide',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'PQ Diss & Theses'        => array(
      'url'                   => 'https://search.proquest.com/pqdtscieng/results/1362AF8173243B02C7B/1/$5bqueryType$3dbasic:pqdtscieng$3b+sortType$3drelevance$3b+searchTerms$3d$5b$3cAND$7ccitationBodyTags:###$3e$5d$3b+searchParameters$3d$7bNAVIGATORS$3dsourcetypenav,pubtitlenav,languagenav$28filter$3d200$2f0$2f*$29,decadenav$28filter$3d110$2f0$2f*,sort$3dname$2fascending$29,yearnav$28filter$3d1100$2f0$2f*,sort$3dname$2fascending$29,yearmonthnav$28filter$3d120$2f0$2f*,sort$3dname$2fascending$29,monthnav$28sort$3dname$2fascending$29,daynav$28sort$3dname$2fascending$29,+RS$3dOP,+chunkSize$3d20,+instance$3dprod.academic,+ftblock$3d163000+8+163008,+removeDuplicates$3dtrue$7d$3b+metaData$3d$7bUsageSearchMode$3dQuickSearch,+dbselections$3ddissertations$7d$5d?accountid=28439',
      'info'           	      => '/resources/more/dissertations.html#/?slide=ProQuest-Dissertations-amp-Theses-mainly-North-Americas',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    )
);
$arrEnginges['more']['Maps'] = array(
    'OpenStreetMap'           => array(
      'url'                   => 'https://nominatim.openstreetmap.org/search.php?q=###&viewbox=8.49%2C47.36%2C8.57%2C47.32',
      'info'           	      => '/resources/more/maps-und-geodata.html#openstreetmap',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'Google Maps'     	      => array(
//    'url'                   => 'https://maps.google.com/maps?q=###&output=embed',
      'url'                   => 'https://search.lib4ri.ch/web/search.handler.php?api=google&scope=maps&find=###',
      'info'           	      => '/resources/more/maps-und-geodata.html#googlemaps',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'map.search.ch'           => array(
//    'url'                   => 'https://map.search.ch/?x=0m&y=0m&z=1&b=&p=&e=&w=640&h=480&s=0&poi_sticky=&poi_default=&home=&words=###&search=Search&from=&to=&w_h=640x480',
      'url'                   => 'https://map.search.ch/###',
      'info'           	      => '/resources/more/maps-und-geodata.html#mapsearch',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'GeoNames'     	      => array(
      'url'                   => 'https://www.geonames.org/search.html?q=###',
      'info'           	      => '/resources/more/maps-und-geodata.html#geonames',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    )
);
$arrEnginges['more']['Patents'] = array(
    'Derwent' 		      => array(
      'noFrameBrowserIntranet' => 'Chrome,Edge,Safari',
      'noFrameBrowserExternal' => 'Firefox,Chrome,Edge,Safari',		/* because there is no network-external access at all */
//    'url'                   => 'https://gateway.isiknowledge.com/gateway/Gateway.cgi?GWVersion=2&SrcApp=LIB4RI_WEB&SrcAuth=LIB4RI&DestApp=DIIDW&ServiceName=TransferToWoS&DestLinkType=GeneralSearchSummary&Func=Links&topic=###',
      'url'                   => 'https://www.webofscience.com/wos/diidw/general-summary?TS=###',
      'info'           	      => '/resources/more/patents.html#/?slide=Derwent-Innovation-Index',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'Espacenet'     	      => array(
      'url'                   => 'https://worldwide.espacenet.com/searchResults?DB=worldwide.espacenet.com&locale=en_EP&query=###',
      'info'           	      => '/resources/more/patents.html#/?slide=Esp-cenet',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    ),
    'Google Patents'          => array(
      'urlOrig'               => 'https://www.google.com/search?hl=en&tbm=pts&q=###',
      'url'                   => '/site/search/find/gpatents.php?hl=en&q=###',
      'info'           	      => '/resources/more/patents.html#/?slide=Google-Patents',
      'replaceTag'            => '###',
      'replaceGermanVowel'    => false,
      'keywordSeparator'      => '+',
      'addBefore'             => false,
      'enabled'               => true,
      'prio'                  => 1,
    )
);

//$arrEnginges['more']['Search the Web'] 	= array(
//    'Wolfram | Alpha'     		=> array(
//    'url'                   => '/site/search/wolframalpha.php?q=###',
//    'url'                   => 'http://www.wolframalpha.com/input/?i=###',
//      'info'           			 	=> '/resources/more/search-the-web.html#wolfram',
//      'replaceTag'            => '###',
//      'replaceGermanVowel'    => false,
//      'keywordSeparator'      => '+',
//      'addBefore'             => false,
//      'enabled'               => true,
//      'prio'                  => 1,
//    ),
//    'Phone Book CH'     			=> array(
//    'url'                   => 'http://tel.local.ch/en/q/?what=###&where=%5BSwitzerland%5D&search=Find+It&rid=q0TI',
//      'info'           			 	=> '/resources/more/search-the-web.html#local',
//      'replaceTag'            => '###',
//      'replaceGermanVowel'    => false,
//      'keywordSeparator'      => '+',
//      'addBefore'             => false,
//      'enabled'               => true,
//      'prio'                  => 1,
//    ),
//    'Google News'     				=> array(
//    'url'                   => '/site/search/gnews.php?hl=en&q=###',
//    'url'                   => 'http://www.google.com/search?hl=en&gl=ch&tbm=nws&q=###',
//      'info'           			 	=> '/resources/more/news-und-newspapers.html#googlenews',
//     	//http://news.google.com/news?q=###&output=embed,
//      'replaceTag'            => '###',
//      'replaceGermanVowel'    => false,
//      'keywordSeparator'      => '+',
//      'addBefore'             => false,
//      'enabled'               => true,
//      'prio'                  => 1,
//    )
//);
